spring:
  application:
    name: industry
  profiles:
    active: test

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate

  thymeleaf:
    cache: false
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/

  session:
    store-type: redis

logging:
  pattern:
    dateformat: HH:mm:ss.SSS



