spring:
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/es
  username: root
  password: root
  tomcat:
   max-active: 100
   max-idle: 200
   initial-size: 20

 redis:
  database: 0
  host: 173.82.240.222
  port: 6379


swagger:
  enabled: true
  title: swagger
  version: 1.0
  description: 接口文档
  base-path: /**
  exclude-path: /error,/login,/home
  contact:
    name: zz
    email: aa@11.com
  ui-config:
    doc-expansion: none

logging:
   level:
    com-bj-industry: debug



